feature/86cuwgj6w-leave-view-review-button-routing: Added routing to …
Monash-FIT3170/Behind-The-Veil pull request #115
Opened 2024-08-19 02:47 UTC by viggy21

Added:

- Routing to dummy review page from bride's past booking tab through the leave/view review button
- Added new mock data (bookings12.json and reviews12.json)
- Added database collection, methods and test cases for Review Collection

2024-08-20 13:32 UTC, RyanAHicks approved these changes

2024-08-20 13:34 UTC, RyanAHicks requested changes
PR looks good, there's just one conflict with the file reviews12.json, rebasing with develop should solve this conflict (I believe Nikki added the file before you haha)

2024-08-22 08:33 UTC, kbib0002 commented
The code itself adheres to conventions and the feature works as expected.
The merge conflicts have been resolved.

Good to merge 👍

2024-08-22 08:33 UTC, kbib0002 approved these changes

2024-08-22 10:50 UTC, RyanAHicks approved these changes

2024-08-22 11:25 UTC, merged