Anusha coded Cancel Booking form with mock data and button.
Monash-FIT3170/Behind-The-Veil pull request #15
Opened 2024-04-27 22:36 UTC by ayad0010

Anusha's code for the cancel booking form. Please review and merge. Thankyou.

2024-04-28 05:42 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/pages/cancel-booking/CancelBooking.jsx
> +            <Button className="bg-secondary-purple hover:bg-secondary-purple-hover">Cancel Booking</Button>
We might need to have a new ticket for this that later adds the DB functionality for this so we don't forget

2024-04-28 05:47 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/pages/cancel-booking/CancelBooking.jsx
is this being called anywhere to view for now? or like a link to the page?

2024-04-28 05:48 UTC, nethbtju reviewed
is this page being called anywhere to view for now? or like a link to the page?

2024-04-28 08:02 UTC, nethbtju requested changes
Refer to comments for changes needed

2024-05-11 13:24 UTC, nethbtju requested changes
Minor changes then approved

2024-05-11 13:24 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/pages/cancel-booking/CancelBooking.jsx
> +            <Button className="bg-gradient-to-r from-bg-gradient-start to-bg-gradient-end">Cancel Booking</Button>
button colour is purple not gradient

2024-05-11 13:24 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/App.jsx
> +>>>>>>> develop
Needs to be removed (my bad sorry)

2024-05-11 15:09 UTC, nethbtju approved these changes
Made minor changes but otherwise vibes

2024-05-11 15:28 UTC, NikkiShao approved these changes
Looks good :)

2024-05-11 16:00 UTC, merged