Feature/86cv684zq messenger inbox component
Monash-FIT3170/Behind-The-Veil pull request #17
Opened 2024-04-28 11:11 UTC by viggy21

Added the messenger inbox feature to the left side of the messages page.

2024-04-28 13:57 UTC, nethbtju requested changes
couple of changes needed

2024-04-28 13:57 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/pages/messages/MessagesPage.jsx
> +        image: '',
From the way the database schema is currently written you will be getting a photoid with the message object which you might have to fetch from the photos db: https://lucid.app/lucidchart/bf2238cb-8db1-4a45-a72d-b6007c65c46e/edit?viewport_loc=-3967%2C-1545%2C10533%2C3907%2C0_0&invitationId=inv_99b49be3-2c60-4b42-a5c7-16051f9d3b7e

2024-04-28 13:57 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/pages/messages/MessagesPage.jsx
> +        image: '',
Let us know if you have a better way you'd like to do it

2024-04-28 13:57 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/pages/messages/MessagesPage.jsx
Add you name as a contributor

2024-04-28 13:57 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/pages/messages/MessagesPage.jsx
Try viewing this in mobile view, it throws everything out of a bit whack haha see if you can get it to scale accordingly

2024-04-28 13:57 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/whiteBackground/whiteBackground.css
> +    @apply mt-16 p-4 w-3/12 h-fit; /*some positioning variables*/
what did this end up doing btw? js curious!

2024-05-12 01:56 UTC, nethbtju requested changes
Changes needed to approve

2024-05-13 15:08 UTC, closed without merging

2024-05-13 15:09 UTC, NikkiShao commented
A new branch was made for messenger inbox, this is now not relevant anymore