Feature/86cuw4czn Services Page
Monash-FIT3170/Behind-The-Veil pull request #29
Opened 2024-05-09 18:35 UTC by NikkiShao

Completed the whole services page including displaying service cards, routing to particular services pages (this is a separate page not covered), pagination of items, etc. The search bar functionality is not covered by this feature.

To test the page with database data, tester/reviewer may need to import some data to their local MongoDB server. Instructions have also been included in the mockdata folder.

2024-05-11 13:54 UTC, nethbtju commented on behind-the-veil-siteroot/imports/api/collections/photo.js
is this suppose to empty?

2024-05-11 16:53 UTC, NikkiShao commented
Please squash all these into 1 commit when merging

2024-05-12 01:33 UTC, nethbtju requested changes
Couple of changes

2024-05-12 01:33 UTC, nethbtju commented on behind-the-veil-siteroot/imports/api/publications/photo.js
Delete!!

2024-05-12 01:33 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/App.jsx
This is weird, it should've have nothing I just merged anushas?

2024-05-12 01:33 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/pages/login/LoginPage.jsx
do we wanna change the naming convention of the page to sign in page ?

2024-05-12 01:33 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/pages/login/LoginPage.jsx
Also this is so weird its as if Kyles stuff doesn't exist on develop

2024-05-12 01:35 UTC, nethbtju commented
Yours seems to have the duplicate commits issue too

2024-05-12 01:49 UTC, nethbtju approved these changes
Looks fine now!

2024-05-12 01:50 UTC, nethbtju approved these changes
All files checked and reviewed no issues

2024-05-12 01:50 UTC, nethbtju approved these changes
Reviewed changes

2024-05-12 02:17 UTC, joshualoongwy approved these changes

2024-05-12 02:19 UTC, merged