Feature/86cv4duft Booking Summary Page
Monash-FIT3170/Behind-The-Veil pull request #33
Opened 2024-05-11 12:55 UTC by nethbtju

This file is accessed through http://localhost:3000/request-booking. Input your booking request details and click next step to make summary appear.

Please double check the profilePhoto stuff works cos my git decided to obliterate it from existence...

2024-05-12 05:12 UTC, joshualoongwy requested changes

2024-05-12 11:59 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/toolTip/ToolTip.js
> +const ToolTip = ({ tipIcon: ToolTipIcon, tipText}) => {
Yeah not bad of an idea I'll look into it rn

2024-05-12 11:59 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/pages/request-booking/booking.css
> +.label {
oh completely missed that. Kinda suck at tailwind rip

2024-05-13 10:34 UTC, nethbtju commented on behind-the-veil-siteroot/imports/ui/components/toolTip/ToolTip.js
> +const ToolTip = ({ tipIcon: ToolTipIcon, tipText}) => {
i added this, can you have a look it works fine on your end?

2024-05-13 10:47 UTC, joshualoongwy commented on behind-the-veil-siteroot/imports/ui/components/pages/home/HomePage.jsx
> +            <div
oh btw, just wondering are we going with the fuzzier design in figma? this is what this branch looks like
![image](https://github.com/Monash-FIT3170/Behind-The-Veil/assets/95511987/8901d0f4-31ab-4770-baa2-67269a1f428c)

2024-05-13 10:51 UTC, joshualoongwy commented on behind-the-veil-siteroot/imports/ui/components/toolTip/ToolTip.js
> +const ToolTip = ({ tipIcon: ToolTipIcon, tipText}) => {
yep tooltip looks fine to me

2024-05-13 10:52 UTC, joshualoongwy commented on behind-the-veil-siteroot/imports/ui/components/pages/request-booking/FormOutput.jsx
> +                <span className="tooltip content-center left-1 ml-2">
i dont think the classes 'tooltip' and 'left-1' do anything here

2024-05-13 10:53 UTC, joshualoongwy commented on behind-the-veil-siteroot/imports/ui/components/pages/request-booking/FormOutput.jsx
> +            <span className={`label min-w-[150px] lg:w-[200px] ${textColor} font-semibold`}>
the class 'label' doesn't do anything anymore so can remove it

2024-05-14 12:57 UTC, joshualoongwy approved these changes

2024-05-14 12:58 UTC, merged