Deprecation error from install dependencies fixed
Monash-FIT3170/Behind-The-Veil pull request #65
Opened 2024-05-17 12:17 UTC by CameronNguyen0

This is a identical branch to the branch in PR https://github.com/Monash-FIT3170/Behind-The-Veil/pull/59
But deprecation error from installing dependencies in the old branch has been fixed now 

Location input now has autoComplete feature from MapBox
Ticket completed:  https://app.clickup.com/t/86cuwqmku
To check navigate to: http://localhost:3000/request-booking
When texts are typed into the Location input box, suggestions are dropped down so the user can click on
Note:
New dependencies are installed so run meteor npm install again
It should appears like this
![image](https://github.com/Monash-FIT3170/Behind-The-Veil/assets/113086379/a63f0383-763f-431c-ae56-6169f7ee9eb3)

2024-05-17 12:55 UTC, RyanAHicks submitted a review, later dismissed
Searching for a location functionality works, shows suggested locations correctly. 

One thing though, upon entering the address and clicking 'next step', the location in booking summary is empty? (Refer to screenshots below) If showing the selected location in booking summary is beyond the scope of this ticket just let me know!

<img width="1063" alt="Screenshot 2024-05-17 at 10 50 18 pm" src="https://github.com/Monash-FIT3170/Behind-The-Veil/assets/163800239/34e72eab-b530-4994-ab52-7f21797ea695">
<img width="764" alt="Screenshot 2024-05-17 at 10 50 32 pm" src="https://github.com/Monash-FIT3170/Behind-The-Veil/assets/163800239/cbed3007-f00a-40a8-ab07-03633b98c873">

2024-05-18 00:02 UTC, kbib0002 commented
Chosen location now appears in Booking Summary, however the suburb is omitted.

2024-05-22 10:33 UTC, nethbtju requested changes
Only two files here, merge has wiped ur work but u can still copy paste it from the drop down that says changes from all commits

2024-05-22 15:48 UTC, CameronNguyen0 commented
@nethbtju @RyanAHicks 
All bugs have been resovled
Location now output in the format specified in figma including street, suburb, zipcode, state

2024-05-23 00:52 UTC, nethbtju approved these changes
It doesn't autofill the whole address - will need to be a bugfix ticket via the QAs

2024-05-23 04:14 UTC, nethbtju approved these changes
Bug ticket must be opened for autofill issue in develop. Will not be merging this to main

2024-05-23 04:16 UTC, merged